apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
spec:
  ingressClassName: nginx # Required in newer Kubernetes versions
  rules:
    - host: hello.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-service
                port:
                  number: 80


# minikube addons enable ingress 
# minikube addons list
# kubectl get ns
# kubectl get all -n ingress-nginx 
# kubectl get pod -n ingress-nginx 
# kubectl get services -n ingress-nginx 
# kubectl apply -f hello.yaml
# kubectl apply -f hello-ingress.yaml
# kubectl get deployment 




# kubectl port-forward -n ingress-nginx svc/ingress-nginx-controller 8080:80
--- # in parallel
# new cmd --
    # curl H "Host: hello.com" http://localhost:8080
    # copy to broweser http://localhost:8080